@InnowiseClinic.Microservices.Documents.Presentation_HostAddress = http://localhost:5095

GET {{InnowiseClinic.Microservices.Documents.Presentation_HostAddress}}/weatherforecast/
Accept: application/json

###
